In [2]:
import torch

In [ ]:
# Define a PyTorch tensor with shape (3,4) containing integers
# from 1 to 12 sequentially. Get creative to define it as cleanly as
# possible.
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [ ]:
# Change the dtype of the above tensor to float32.
print(f"Current type of tensor 'a': {a.dtype}")
a = a.to(torch.float32)
print(f"Changed type of tensor 'a': {a.dtype}")

Current type of tensor 'a': torch.float32
Changed type of tensor 'a': torch.float32


In [9]:
# Transpose its rows and columns (no need to change the input,
# just return a view).
print(f"Current tensor: {a}")
print(f"Transpose of the tensor: {a.transpose(dim0=0, dim1=1)}")

Current tensor: tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
Transpose of the tensor: tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])


In [13]:
# Try transpose with a 3-D tensor
three_d_tensor = torch.arange(1, 25).reshape(2, 3, 4)
print(three_d_tensor)
print(three_d_tensor.transpose(0, 1))
print(three_d_tensor.transpose(1, 2))
print(three_d_tensor.transpose(0, 2))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
tensor([[[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]],

        [[ 4, 16],
         [ 8, 20],
         [12, 24]]])


In [15]:
# Reshape it to take the shape (4,3) (no need to change the input,
# just return a view)
print(a)
a.reshape(4, 3)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [20]:
# [Masking] Given a PyTorch tensor containing negative and positive integers, replace
# all the negative integers with -1.
b = torch.tensor([[1, -2, 3], [-4, -3, 0]])
print(b)
neg_mask = b < 0
print(neg_mask)
b[neg_mask] = -1
print(b)

tensor([[ 1, -2,  3],
        [-4, -3,  0]])
tensor([[False,  True, False],
        [ True,  True, False]])
tensor([[ 1, -1,  3],
        [-1, -1,  0]])


In [26]:
# Given 2D PyTorch tensors a and b, defined as
#   a = torch.tensor([[-3,1,2],[-1,0,6]])
#   b = torch.tensor([[0,1,0],[1,0,1]])
# For each of the tensors, do the following:
# 1. Check if there is any occurrence of the values 0 or 1.
# 2. Check if all the values of the tensor belong to the set 0, 1.
a = torch.tensor([[-3,1,2],[-1,0,6]])
b = torch.tensor([[0,1,0],[1,0,1]])
c = torch.tensor([0, 1])
torch.isin(a, c)

# Part-1
print(torch.isin(a, c).any().item())
print(torch.isin(b, c).any().item())

# Part-2
print(torch.isin(a, c).all().item())
print(torch.isin(b, c).all().item())

True
True
False
True


In [35]:
# [Clipping] Given a 2D PyTorch tensor,
# 1. Return a tensor with all its elements clipped between 0 and 1.
#   So all the elements less than 0 should be changed to 0, all those
#   greater than 1 should be changed to 1, and those between 0 and 1
#   should be left unchanged.
# 2. Return a clipping of only its first row between 0 and 1.
# 3. Change the input tensor itself, clipping its first row between 0 and 1.
# You can start with the following input tensor:
#   a = torch.tensor([[-1, 0, 0.2, 1, 1.5],[2, -2, 0, 1, 0.4]])

a = torch.tensor([[-1, 0, 0.2, 1, 1.5],[2, -2, 0, 1, 0.4]])

# Part-1
print(f"clamp: {a.clamp(min=0, max=1)}")
print(f"clip: {a.clip(min=0, max=1)}") # Just an alias for clamp()
print(f"clamp: {torch.clamp(a, min=0, max=1)}")

# Part-2
print(f"{torch.clamp(a[0, :], min=0, max=1)}")
print(f"{a}")

# Part-3
a[0, :].clamp_(min=0, max=1) # The underscore(_) suffix is the in-place version for the corresponding clamp operation
print(f"{a}")

clamp: tensor([[0.0000, 0.0000, 0.2000, 1.0000, 1.0000],
        [1.0000, 0.0000, 0.0000, 1.0000, 0.4000]])
clip: tensor([[0.0000, 0.0000, 0.2000, 1.0000, 1.0000],
        [1.0000, 0.0000, 0.0000, 1.0000, 0.4000]])
clamp: tensor([[0.0000, 0.0000, 0.2000, 1.0000, 1.0000],
        [1.0000, 0.0000, 0.0000, 1.0000, 0.4000]])
tensor([0.0000, 0.0000, 0.2000, 1.0000, 1.0000])
tensor([[-1.0000,  0.0000,  0.2000,  1.0000,  1.5000],
        [ 2.0000, -2.0000,  0.0000,  1.0000,  0.4000]])
tensor([[ 0.0000,  0.0000,  0.2000,  1.0000,  1.0000],
        [ 2.0000, -2.0000,  0.0000,  1.0000,  0.4000]])


In [11]:
# In PyTorch, image datasets are stored in the format (N, C, H, W), where N is the
# number of images in the set (or the batch), C is the number of channels (usually 3 for
# a color image, corresponding to red, green, and blue), H is the image height, and W
# is the image width. Given a tensor containing an image dataset of size [128, 3, 224,
# 224], perform the following slicing operations:
# 1. Select the first 32 images of the set.
# 2. Select only channel 0 for all the samples in the set (note
# that the output size must be [128, 1, 224, 224], and not [128,
# 224, 224]).
# 3. For each image in the set, and for all the channels, select pixels
# with height from 16 to 128 (inclusive of 16, but not 128), and
# select every alternate pixel from the width, starting from the
# beginning.
# You can work with a random tensor initialized as follows:
#   image_set = torch.rand([128, 3, 224, 224])

image_set = torch.rand([128, 3, 224, 224])

# Part-1:
print(image_set[:32, :, :, :].size())

# Part-2:
print(image_set[:, :1, :, :].size())

# Part-3:
print(image_set[:, :, 16:128, ::2].size())

torch.Size([32, 3, 224, 224])
torch.Size([128, 1, 224, 224])
torch.Size([128, 3, 112, 112])


In [14]:
# Given a 2D tensor, calculate the index of the maximum element in every row. Repeat
# the same for each column.
# HINT: Use torch.argmax function.
# You can start with the following input tensor to test your code:
#   input_tensor = torch.tensor([[1,2,3,4,5,3],[3,5,6,3,2,1]])

input_tensor = torch.tensor([[1,2,3,4,5,3],[3,5,6,3,2,1]])

print(f"Row-wise max: {input_tensor.argmax(dim=1)}")

print(f"Column-wise max: {input_tensor.argmax(dim=0)}")

Row-wise max: tensor([4, 2])
Column-wise max: tensor([1, 1, 1, 0, 0, 0])


In [19]:
# Given two 1D tensors of the same length, calculate the number of indices where they
# have the same values.
# You can use the following two input tensors to test your code:
#   target = torch.tensor([1,3,4,5,6,7])
#   predictions = torch.tensor([2,3,4,6,3,7])

target = torch.tensor([1,3,4,5,6,7])
predictions = torch.tensor([2,3,4,6,3,7])

print((target == predictions))
print((target == predictions).long())
print((target == predictions).long().sum())
print((target == predictions).long().sum().item())


tensor([False,  True,  True, False, False,  True])
tensor([0, 1, 1, 0, 0, 1])
tensor(3)
3


In [22]:
# Given a tensor, return a tensor with all dimensions of size 1 removed.
# You can use the following tensor:
#   a = torch.ones([4,1,3,2,1])
# HINT: torch.squeeze()

a = torch.ones([4,1,3,2,1])

print(a.squeeze().size())

torch.Size([4, 3, 2])


In [25]:
# Given a 1D tensor of size (n,), return a 2D tensor which has size (n,1), so that each
# row of this tensor has a single element of the input tensor in the same order.
# You can work with:
#   

a = torch.arange(6)

print(a)

print(a.unsqueeze(dim=1))

tensor([0, 1, 2, 3, 4, 5])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
